AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'spec/fabricators/**/*'
    - 'node_modules/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Bundler/OrderedGems:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/AccessModifierDeclarations:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Lint/MissingCopEnableDirective:
  Enabled: false
